-- DATABASE SCHEMA FOR SUPABASE (POSTGRESQL)
-- Copy and paste this script directly into your Supabase SQL Editor (Dashboard > SQL Editor > New Query)

-- 1. PROFILES TABLE (Extends Supabase Auth users table)
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    nin TEXT,
    country TEXT,
    state_region TEXT,
    city TEXT,
    is_organisation BOOLEAN DEFAULT FALSE,
    org_name TEXT,
    org_role TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS) on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- Make NIN unique where entered (permits multiple empty or null values)
CREATE UNIQUE INDEX IF NOT EXISTS profiles_nin_unique_idx ON public.profiles (nin) WHERE (nin IS NOT NULL AND nin <> '');

-- Create policies for profiles
CREATE POLICY "Allow public read profiles" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Allow users to insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Allow users to update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Create a trigger function to automatically populate public.profiles on new signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (
    id, 
    full_name, 
    phone,
    first_name,
    last_name,
    nin,
    country,
    state_region,
    city,
    is_organisation,
    org_name,
    org_role
  )
  VALUES (
    new.id,
    COALESCE(new.raw_user_meta_data->>'first_name', '') || ' ' || COALESCE(new.raw_user_meta_data->>'last_name', ''),
    COALESCE(new.raw_user_meta_data->>'phone', ''),
    COALESCE(new.raw_user_meta_data->>'first_name', ''),
    COALESCE(new.raw_user_meta_data->>'last_name', ''),
    COALESCE(new.raw_user_meta_data->>'nin', ''),
    COALESCE(new.raw_user_meta_data->>'country', 'Nigeria'),
    COALESCE(new.raw_user_meta_data->>'state_region', 'Abia'),
    COALESCE(new.raw_user_meta_data->>'city', ''),
    COALESCE((new.raw_user_meta_data->>'is_organisation')::boolean, false),
    COALESCE(new.raw_user_meta_data->>'org_name', ''),
    COALESCE(new.raw_user_meta_data->>'org_role', '')
  );
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger execution rule
CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


-- 2. CRIME REPORTS TABLE
CREATE TABLE IF NOT EXISTS public.crime_reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference_no TEXT UNIQUE NOT NULL,
    user_id UUID REFERENCES auth.users ON DELETE SET NULL,
    anonymous SMALLINT DEFAULT 0 NOT NULL, -- 0 = registered, 1 = anonymous
    crime_type TEXT NOT NULL,
    description TEXT NOT NULL,
    location TEXT NOT NULL,
    crime_date DATE NOT NULL,
    crime_time TIME NOT NULL,
    image TEXT, -- path to uploaded evidence image in bucket
    status TEXT DEFAULT 'Pending' NOT NULL, -- Pending, Assigned, Under Investigation, Resolved, Closed
    reporter_name TEXT,
    reporter_phone TEXT,
    reporter_email TEXT,
    reporter_nin TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.crime_reports ENABLE ROW LEVEL SECURITY;

-- Policies for crime reports
CREATE POLICY "Allow public read access to track report status" ON public.crime_reports FOR SELECT USING (true);
CREATE POLICY "Allow public inserts for anonymous reporting" ON public.crime_reports FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow users to view their own reports" ON public.crime_reports FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Allow officers/admins full access" ON public.crime_reports FOR ALL USING (true);


-- 3. ADMINS TABLE (Police Officers)
CREATE TABLE IF NOT EXISTS public.admins (
    admin_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL, -- Securely stored hashed password
    role TEXT NOT NULL, -- Super Admin, Investigating Officer
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.admins ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow read admins" ON public.admins FOR SELECT USING (true);
CREATE POLICY "Allow full admins management" ON public.admins FOR ALL USING (true);

-- Insert a default Super Admin (Password is 'admin123' - you can change this in management dashboard)
-- Note: MD5/SHA256 representation or custom hash verification can be configured.
INSERT INTO public.admins (full_name, email, username, password, role)
VALUES ('Super Admin', 'admin@abiapolice.gov.ng', 'admin', 'admin123', 'Super Admin')
ON CONFLICT (username) DO NOTHING;


-- 4. CASE ASSIGNMENTS TABLE
CREATE TABLE IF NOT EXISTS public.case_assignments (
    assignment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT REFERENCES public.crime_reports(report_id) ON DELETE CASCADE,
    admin_id BIGINT REFERENCES public.admins(admin_id) ON DELETE CASCADE,
    assigned_date TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.case_assignments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all assignments access" ON public.case_assignments FOR ALL USING (true);


-- 5. STATUS HISTORY TABLE (Audit logs of status changes)
CREATE TABLE IF NOT EXISTS public.status_history (
    history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_id BIGINT REFERENCES public.crime_reports(report_id) ON DELETE CASCADE,
    old_status TEXT NOT NULL,
    new_status TEXT NOT NULL,
    updated_by_name TEXT NOT NULL, -- Name of officer/admin who changed it
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

ALTER TABLE public.status_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow all status history logs access" ON public.status_history FOR ALL USING (true);


-- 6. STORAGE BUCKET CONFIGURATION
-- Note: Go to Supabase > Storage, create a public bucket named "evidence"
-- Paste the SQL below to configure policy rules for evidence bucket uploads
-- CREATE POLICY "Allow anyone to upload evidence images" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'evidence');
-- CREATE POLICY "Allow anyone to read evidence images" ON storage.objects FOR SELECT USING (bucket_id = 'evidence');
